version: "3"
services:
  backend:
    image: node-backend-app
    ports:
      - "3333:3333"
    networks:
      - app-network

  frontend:
    image: react-native-app
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
